CREATE TABLE IF NOT EXISTS NOTI_LOG (
  LOG_ID  INT AUTO_INCREMENT NOT NULL,
  NOTI_TYPE VARCHAR(45) NOT NULL,
  PHONE_NUMBER VARCHAR(100) NOT NULL,
  CREATE_AT DATETIME NOT NULL,

  PRIMARY KEY(LOG_ID)
);

-- TODO : #1 MEMBER 테이블 생성.
-- TODO : #1 create MEMBER table.
CREATE TABLE IF NOT EXISTS MEMBER (
	NAME VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(100) NOT NULL,

	PRIMARY KEY(NAME)
);
